server:
  port: 8080
  servlet:
    context-path: /watchez
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: "jdbc:mysql://svr-freehost.vinahost.vn:3306/cqfzvzkv_watchez?useSSL=false&allowPublicKeyRetrieval=&characterEncoding=utf8mb4&serverTimezone=UTC"
    username: cqfzvzkv_thuanht
    password: thuan2k3yg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "b15cc2a6a69c57e73b62faad7a59d3f70a32a3f17185ab6c7a499208ff9aaea9"