server:
  port: 8080
  servlet:
    context-path: /watchez

spring:
  datasource:
    url: "jdbc:mysql://svr-freehost.vinahost.vn:3306/cqfzvzkv_watchez?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: cqfzvzkv_thuanht
    password: thuan2k3yg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true